services:
  - type: web
    name: acadmate-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: acadmate-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: acadmate-db
    plan: free
    databaseName: acadmate_db
    user: acadmate_user
